"""Update models: add source, category, roles, timestamps, explanation_type, recommendation table

Revision ID: e424d0e9a182
Revises: 63acd37ab5ba
Create Date: 2026-03-10 15:08:56.492238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e424d0e9a182'
down_revision: Union[str, None] = '63acd37ab5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('explanations',
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('explanation_type', sa.String(length=50), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('similar_paper_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_explanations_paper_id'), 'explanations', ['paper_id'], unique=False)
    op.create_index(op.f('ix_explanations_user_id'), 'explanations', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('algorithm', sa.String(length=100), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('helpful', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_paper_id'), 'recommendations', ['paper_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.add_column('embeddings', sa.Column('model_version', sa.String(length=50), nullable=False, server_default='unknown'))
    op.add_column('embeddings', sa.Column('embedding_quality_score', sa.Float(), nullable=True))
    op.add_column('interactions', sa.Column('weight', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('interactions', sa.Column('rating', sa.Integer(), nullable=True))
    op.add_column('interactions', sa.Column('interaction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_interactions_interaction_timestamp'), 'interactions', ['interaction_timestamp'], unique=False)
    op.create_unique_constraint('uq_user_paper_interaction', 'interactions', ['user_id', 'paper_id', 'interaction_type'])
    op.add_column('papers', sa.Column('category', sa.String(length=100), nullable=False, server_default='Other'))
    op.add_column('papers', sa.Column('source', sa.String(length=50), nullable=False, server_default='Other'))
    op.alter_column('papers', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('papers_doi_key', 'papers', type_='unique')
    op.create_index(op.f('ix_papers_category'), 'papers', ['category'], unique=False)
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=True)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_venue'), 'papers', ['venue'], unique=False)
    op.create_unique_constraint('uq_paper_title_authors', 'papers', ['title', 'authors'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    userrole = postgresql.ENUM('USER', 'ADMIN', 'RESEARCHER', name='userrole', create_type=False)
    userrole.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', sa.Enum('USER', 'ADMIN', 'RESEARCHER', name='userrole', create_constraint=True), nullable=False, server_default='USER'))
    op.add_column('users', sa.Column('preferred_categories', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_column('users', 'preferred_categories')
    op.drop_column('users', 'role')
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    op.drop_column('users', 'is_active')
    op.drop_constraint('uq_paper_title_authors', 'papers', type_='unique')
    op.drop_index(op.f('ix_papers_venue'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_index(op.f('ix_papers_category'), table_name='papers')
    op.create_unique_constraint('papers_doi_key', 'papers', ['doi'])
    op.alter_column('papers', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('papers', 'source')
    op.drop_column('papers', 'category')
    op.drop_constraint('uq_user_paper_interaction', 'interactions', type_='unique')
    op.drop_index(op.f('ix_interactions_interaction_timestamp'), table_name='interactions')
    op.drop_column('interactions', 'interaction_timestamp')
    op.drop_column('interactions', 'rating')
    op.drop_column('interactions', 'weight')
    op.drop_column('embeddings', 'embedding_quality_score')
    op.drop_column('embeddings', 'model_version')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_paper_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_explanations_user_id'), table_name='explanations')
    op.drop_index(op.f('ix_explanations_paper_id'), table_name='explanations')
    op.drop_table('explanations')
    # ### end Alembic commands ###
